### ISSUE TITLE
Project won't compile.

### ISSUE THREAD

**Issue by skynet1** [hasktorch/hasktorch#465]
Got this error message from compiling hasktorch with "cabal v1-install hasktorch": 
Resolving dependencies...
Starting     hasktorch-0.2.0.0
Building     hasktorch-0.2.0.0
Failed to install hasktorch-0.2.0.0
Build log ( /home/noah/.cabal/logs/ghc-8.6.5/hasktorch-0.2.0.0-Bv6cnPNrF0BCdDqdLMEBDj.log ):
cabal: Entering directory 'hasktorch/'
Configuring hasktorch-0.2.0.0...
Preprocessing library for hasktorch-0.2.0.0..
Building library for hasktorch-0.2.0.0..
[40 of 62] Compiling Torch.Typed.Parameter ( src/Torch/Typed/Parameter.hs, dist/build/Torch/Typed/Parameter.o )

src/Torch/Typed/Parameter.hs:195:8: error:
    • Type indexes must match class instance head
      Expected: Parameters (HList '[])
        Actual: Parameters (HList '[])
    • In the type instance declaration for ‘Parameters’
      In the instance declaration for ‘Parameterized (HList '[])’
    |
195 |   type Parameters (HList '[]) = '[]
    |        ^^^^^^^^^^
cabal: Leaving directory 'hasktorch/'
cabal: Error: some packages failed to install:
hasktorch-0.2.0.0-Bv6cnPNrF0BCdDqdLMEBDj failed during the building phase. The
exception was:
ExitFailure 1
ghc version 8.6.5
cabal version 3.2

**Comment by tscholak** [comment]
Hello @skynet1. We do not support ghc 8.6 any longer. Please use 8.8.
You may also want to switch to `cabal new-build` instead of `v1`.

**Comment by tscholak** [comment]
@skynet1 did it work?
If you need a bit more hands-on help from the team, consider joining our slack. Just send an email to hasktorch@gmail.com to get invited.

**Comment by skynet1** [comment]
I tried upgrading to ghc 8.10, and now I keep getting errors about there being missing files in unordered-containers. I think I may have screwed up my ghc install at some point in the past.

**Comment by tscholak** [comment]
Hi @skynet1, hm, while the officially supported ghc version is 8.8, there are several people who successfully worked with 8.10 recently. maybe cleaning your cabal cache will help.

**Comment by skynet1** [comment]
I tried removing the ~/.cabal folder, and the ~/.ghc folder and reinstalling things but that didn't help. Also while I was troubleshooting this I found out that it will often complain about methods, functions, and classes being declared twice in 
/usr/include/torch/csrc/api/include/torch/ordered_dict.h, but it doesn't when I remove all the code from that file.

**Comment by tscholak** [comment]
Hi skynet1, I'm sorry that you have so much trouble. I'm tapping in the dark as to the causes.
Can you tell me your operating system? Can you also write down the steps you took from the moment you cloned the repo to where it fails? Maybe I can reproduce this.
You may also want to look at these commands, https://github.com/hasktorch/hasktorch/blob/master/.github/workflows/cabal-linux.yml#L24-L30. These are run as part of our CI tests.

**Comment by skynet1** [comment]
The OS is Arch Linux.
The script for reproducing it is here: https://gist.github.com/skynet1/b369e9ed2bb379c9b29693f4c1f9b139

**Comment by tscholak** [comment]
Hi, thanks for posting this gist, I have a better idea what you're trying to do.
```
mv libtorch/lib/* /usr/lib/
mv libtorch/include/* /usr/include/

cabal --lib install ./libtorch-ffi-helper/
cabal --lib install ./libtorch-ffi/
cabal --lib install ./hasktorch/
```
It seems you are trying to install libtorch and hasktorch system-wide as a library.
Hasktorch 0.2 is pre-release software. It's very much experimental and subject to frequent change.
It recommend using it in a sandboxed nix-style build environment instead.

I don't know if the problems you are seeing are related to the system-wide installation.
I do not have Arch linux installed myself, and I can't try to reproduce your problem myself therefore.
I will pass this on to the community.

**Comment by austinvhuang** [comment]
If you're using cabal, make sure you run `./setup.cabal.sh` - we're in the middle of an overhaul with the README and this should be included in a separate section for cabal users that doesn't exist right now.

You don't need to use nix as a dependency (I don't), but it does seem like something related to referencing the right include/lib locations in the build. 

Would echo @tscholak 's suggestion about the slack via hasktorch@gmail.com - can try to tackle it together there. Thanks for trying things out.

**Comment by austinvhuang** [comment]
we'll update the README with more detail, but you might take a look at the cabal / linux CI process to cross-reference against that. https://github.com/hasktorch/hasktorch/blob/master/.github/workflows/cabal-linux.yml
